### PR TITLE
feat(typescript): Allow to pass type params for response data type

### LINKED ISSUE #47: Re-visit typescript parameters
This is the error and no-one has yet been able to fix it. Maybe sometime later it will be obvious how to fix the issue
```
Type '(<T extends GraphQlQueryResponse>(query: string | Parameters, options?: Parameters | undefined) => Promise<{ [key: string]: any; } | null>) & { defaults: (newDefaults: Parameters) => graphql; endpoint: endpoint; }' is not assignable to type 'graphql'.
  Type 'Promise<{ [key: string]: any; } | null>' is not assignable to type 'Promise<GraphQlQueryResponse>'.
    Type '{ [key: string]: any; } | null' is not assignable to type 'GraphQlQueryResponse'.
      Type 'null' is not assignable to type 'GraphQlQueryResponse'.
```

### PR DESCRIPTION
**Pull request by wolfy1339**
Fixes #47
Reverts #46

### CODE REVIEW

**Comment by gr2m** [comment]
Nice! 

I wonder if we should document the usage of the Typescript parameter in the README?

**Comment by wolfy1339** [comment]
It certainly could be documented in the README, though I'm unsure how it would be documented.

All it does is pass the user-provided type to `@octokit/request`, which is used as the return type for the final `graphql()` function

**Comment by gr2m** [comment]
ping @wolfy1339

**Comment by gr2m** [comment]
closing due to inactivity. Please feel free to reopen, or create a new pull request :)

**Pull request closed without merging**
