### PR TITLE
feat: add `mediaType` to non variable options

### PR DESCRIPTION
**Pull request by os-jsplopes**
Added missing mediaType parameter to non variable options.

Fixes https://github.com/octokit/graphql.js/issues/85

### CODE REVIEW

**Comment by dominguezcelada** [comment]
Fixes https://github.com/octokit/graphql.js/issues/85

**Comment by dominguezcelada** [comment]
> The change looks good, but could you please add a test, so we don't accidentally break that feature in future? The test would go here: https://github.com/octokit/graphql.js/blob/master/test/graphql.test.ts

I can help with that if you want @os-jsplopes :)

**Comment by os-jsplopes** [comment]
@gr2m Test to mediaType added. 
I also removed/replaced the local **RequestOptions** type with the **OctokitTypes.RequestOptions**.

@dominguezcelada Thank you for your availability to help me 👍. But I've already added them, fell free to comment 😄 .

**Comment by dominguezcelada** [comment]
> @gr2m Test to mediaType added.
> I also removed/replaced the local **RequestOptions** type with the **OctokitTypes.RequestOptions**.
> 
> @dominguezcelada Thank you for your availability to help me 👍. But I've already added them, fell free to comment 😄 .

Great @os-jsplopes ! Thanks

Looks good to me but you have conflicts with master branch apparently! ;)

**Comment by gr2m** [comment]
I'm sorry there are conflicts due to recent change in master, if you don't mind, could you look into resolving them?

**Comment by os-jsplopes** [comment]
@gr2m Done!

**Pull request merged**
